# Generated by Django 3.2.7 on 2021-09-16 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('mission', models.TextField()),
                ('impact', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_of', to='accounts.user')),
                ('signers', models.ManyToManyField(blank=True, related_name='signed', to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('unit', models.CharField(db_index=True, max_length=50, verbose_name='units')),
                ('uamount', models.FloatField()),
                ('frequency', models.CharField(choices=[('O', ' Once '), ('D', ' Daily '), ('W', ' Weekly '), ('M', ' Monthly '), ('Y', ' Yearly ')], default='D', max_length=1)),
                ('created', models.DateField(auto_now_add=True)),
                ('parent_pledge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action', related_query_name='actions', to='services.pledge')),
            ],
        ),
    ]
