# Generated by Django 3.2.7 on 2021-09-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='action_steps',
            field=models.ManyToManyField(blank=True, related_name='u_action', related_query_name='u_actions', to='services.Action'),
        ),
    ]
